server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: http://localhost/nacos/
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'



