server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:9000 #nacos服务注册中心
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'