server:
  port: 3000

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashuanger/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:6000/eureka   #单机版
#      defaultZone: http://localhost:6000/eureka,http://localhost:6001/eureka   #集群版


##rabbitmq相关配置
#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest
#
###rabbitmq相关配置,暴露bus刷新配置的端点
#management:
#  endpoints: #暴露bus刷新配置的端点
#    web:
#      exposure:
#        include: 'bus-refresh'

