server:
  port: 9000

spring:
  application:
    name: cloud-geteway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route  #路由的ID，没有固定规则，但是要求唯一
          uri:  http://localhost:8010    #匹配规则之后提供的路由地址
          predicates:
          - Path=/payment/get/**      #断言，路由相匹配的进行路由

        - id: payment_route2 #路由的ID，没有固定规则，但是要求唯一
          uri:  http://localhost:8010    #匹配规则之后提供的路由地址
          predicates:
          - Path=/payment/lb/**      #断言，路由相匹配的进行路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:6000/eureka
