server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0-1之间，1表示全部采集
      probability: 1
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone:  http://localhost:6000/eureka   #单机版
#      defaultZone: http://localhost:6000/eureka,http://localhost:6001/eureka   #集群版

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xsz.springcloud.service: debug
    com.xsz.springcloud.controller: debug
